# Site settings
title: Rahul Goel Blog # site title
description: >- # site description
  
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: /assets/img/avatar.gif # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Rahul Goel # author name
  bio: >- # tell to the world
    He's writing code since 2017 freshly out of school. Now pursuing an engineering degree from National Institute of Technology Delhi. 
    Loves working in Python, Go and anything else he finds fancy. He's been learning TDD and applying his skills everyday. 
    Also a hobby problem solver on <a href="https://leetcode.com/doctorxeno/" target="_blank" rel="noopener">@leetcode</a>.
  username: doctorzeno, raaa # general username
  github: Rahul-NITD # github username
  twitter: asdfagbagog # twitter username
  email: rgoel1729@gmail.com # email adress
  avatar: /assets/img/avatar.gif # change with your own avatar

# URL settings
url: "https://rahul-goel-blog.vercel.app/" #
baseurl: ""
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
